export const allQuestions = [
    "What's your favorite movie?",
    "Do you have any pets?",
    "What's your dream job?",
    "What was the last book you read?",
    "Do you like to travel? If so, where?",
    "What’s your favorite food?",
    "Do you play any sports?",
    "What’s your go-to hobby?",
    "If you could live anywhere in the world, where would it be?",
    "What's something you're passionate about?",
    "Do you believe in aliens?",
    "What’s your biggest fear?",
    "What’s your favorite season of the year?",
    "Are you more of an introvert or extrovert?",
    "Do you like watching TV or movies more?",
    "What’s one skill you’d love to learn?",
    "What was your childhood dream job?",
    "What’s your favorite holiday?",
    "If you could meet anyone, dead or alive, who would it be?",
    "What’s your favorite type of music?",
    "Do you enjoy cooking? What’s your signature dish?",
    "Do you prefer the city or the countryside?",
    "What’s your favorite way to relax?",
    "Do you like puzzles or games?",
    "What’s your biggest achievement?",
    "Do you believe in luck?",
    "If you could time travel, where and when would you go?",
    "What’s your most memorable experience?",
    "What’s one thing you’re grateful for?",
    "Do you like spending time alone or with others?"
];
